# Generated by Django 4.2 on 2023-04-25 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=250)),
                ("text", models.TextField(default="")),
                ("since", models.DateTimeField()),
                ("creator_email", models.EmailField(max_length=254)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in Bearbeitung", "in Bearbeitung"),
                            ("nicht lösbar", "nicht lösbar"),
                            ("reserveiert", "reserviert"),
                        ],
                        max_length=200,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("labels", models.TextField(null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
